import { School, Lab, Category, Item, Loan } from "@/types/database";

// Mock School
export const mockSchool: School = {
  id: "11111111-1111-4111-8111-111111111111",
  name: "SMA Negeri 1 Jakarta",
  address: "Jl. Pendidikan No. 1, Jakarta Pusat",
  logo_url: null,
  created_at: new Date().toISOString(),
};

// Mock Labs
export const mockLabs: Lab[] = [
  {
    id: "22222222-2222-4222-8222-222222222222",
    school_id: "11111111-1111-4111-8111-111111111111",
    name: "Lab Kimia",
    category: "Sains",
    pic_name: "Budi Santoso",
    location: "Gedung A Lt. 2",
    created_at: new Date().toISOString(),
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    school_id: "11111111-1111-4111-8111-111111111111",
    name: "Lab Fisika",
    category: "Sains",
    pic_name: "Dewi Lestari",
    location: "Gedung A Lt. 3",
    created_at: new Date().toISOString(),
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    school_id: "11111111-1111-4111-8111-111111111111",
    name: "Lab Komputer",
    category: "Teknologi",
    pic_name: "Andi Wijaya",
    location: "Gedung B Lt. 1",
    created_at: new Date().toISOString(),
  },
];

// Mock Categories for Lab Kimia
export const mockCategoriesKimia: Category[] = [
  {
    id: "cat-kim-1",
    lab_id: "mock-lab-1",
    name: "Peralatan Glass",
    type: "asset",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-kim-2",
    lab_id: "mock-lab-1",
    name: "Bahan Kimia",
    type: "consumable",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-kim-3",
    lab_id: "mock-lab-1",
    name: "Alat Ukur",
    type: "asset",
    created_at: new Date().toISOString(),
  },
];

// Mock Categories for Lab Fisika
export const mockCategoriesFisika: Category[] = [
  {
    id: "cat-fis-1",
    lab_id: "mock-lab-2",
    name: "Alat Listrik",
    type: "asset",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-fis-2",
    lab_id: "mock-lab-2",
    name: "Alat Mekanik",
    type: "asset",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-fis-3",
    lab_id: "mock-lab-2",
    name: "Bahan Praktikum",
    type: "consumable",
    created_at: new Date().toISOString(),
  },
];

// Mock Categories for Lab Komputer
export const mockCategoriesKomputer: Category[] = [
  {
    id: "cat-kom-1",
    lab_id: "mock-lab-3",
    name: "Perangkat Keras",
    type: "asset",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-kom-2",
    lab_id: "mock-lab-3",
    name: "Perangkat Lunak",
    type: "consumable",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-kom-3",
    lab_id: "mock-lab-3",
    name: "Jaringan",
    type: "asset",
    created_at: new Date().toISOString(),
  },
];

// Mock Items for Lab Kimia
export const mockItemsKimia: Item[] = [
  {
    id: "item-kim-1",
    lab_id: "mock-lab-1",
    category_id: "cat-kim-1",
    name: "Mikroskop Binokuler",
    code: "KIM-001",
    type: "alat",
    total_qty: 15,
    available_qty: 12,
    unit: "pcs",
    condition: "baik",
    location_rack: "Rak A-1",
    min_stock_alert: 5,
    specs_detail:
      "Mikroskop binokuler 1000x dengan lampu LED, lensa achromatic",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-kim-2",
    lab_id: "mock-lab-1",
    category_id: "cat-kim-1",
    name: "Tabung Reaksi",
    code: "KIM-002",
    type: "alat",
    total_qty: 50,
    available_qty: 45,
    unit: "pcs",
    condition: "baik",
    location_rack: "Rak B-2",
    min_stock_alert: 10,
    specs_detail: "Tabung reaksi kaca borosilikat 10ml, tahan panas",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-kim-3",
    lab_id: "mock-lab-1",
    category_id: "cat-kim-2",
    name: "Asam Sulfat",
    code: "KIM-003",
    type: "bahan",
    total_qty: 2000,
    available_qty: 500,
    unit: "ml",
    condition: "baik",
    location_rack: "Lemari B3",
    min_stock_alert: 1000,
    specs_detail: "Asam sulfat 98%, konsentrasi tinggi",
    expired_date: "2025-12-31",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-kim-4",
    lab_id: "mock-lab-1",
    category_id: "cat-kim-2",
    name: "Natrium Klorida",
    code: "KIM-004",
    type: "bahan",
    total_qty: 1000,
    available_qty: 50,
    unit: "gr",
    condition: "baik",
    location_rack: "Lemari B1",
    min_stock_alert: 200,
    specs_detail: "Garam dapur grade laboratorium, kemurnian 99.5%",
    expired_date: "2026-06-30",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-kim-5",
    lab_id: "mock-lab-1",
    category_id: "cat-kim-1",
    name: "Erlenmeyer Flask",
    code: "KIM-005",
    type: "alat",
    total_qty: 30,
    available_qty: 28,
    unit: "pcs",
    condition: "baik",
    location_rack: "Rak B-1",
    min_stock_alert: 8,
    specs_detail: "Erlenmeyer flask 250ml, kaca borosilikat",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-kim-6",
    lab_id: "mock-lab-1",
    category_id: "cat-kim-3",
    name: "Timbangan Analitik",
    code: "KIM-006",
    type: "alat",
    total_qty: 5,
    available_qty: 4,
    unit: "pcs",
    condition: "baik",
    location_rack: "Meja Timbangan",
    min_stock_alert: 2,
    specs_detail: "Timbangan analitik 0.01g, dengan kalibrasi otomatis",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-kim-7",
    lab_id: "mock-lab-1",
    category_id: "cat-kim-2",
    name: "Hidrogen Klorida",
    code: "KIM-007",
    type: "bahan",
    total_qty: 1500,
    available_qty: 300,
    unit: "ml",
    condition: "baik",
    location_rack: "Lemari B2",
    min_stock_alert: 500,
    specs_detail: "HCl 1M, larutan standar",
    expired_date: "2025-08-15",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-kim-8",
    lab_id: "mock-lab-1",
    category_id: "cat-kim-1",
    name: "Gelas Ukur",
    code: "KIM-008",
    type: "alat",
    total_qty: 25,
    available_qty: 22,
    unit: "pcs",
    condition: "rusak_ringan",
    location_rack: "Rak A-2",
    min_stock_alert: 6,
    specs_detail: "Gelas ukur 100ml, skala jelas",
    created_at: new Date().toISOString(),
  },
];

// Mock Items for Lab Fisika
export const mockItemsFisika: Item[] = [
  {
    id: "item-fis-1",
    lab_id: "mock-lab-2",
    category_id: "cat-fis-1",
    name: "Multimeter Digital",
    code: "FIS-001",
    type: "alat",
    total_qty: 20,
    available_qty: 18,
    unit: "pcs",
    condition: "baik",
    location_rack: "Rak C-1",
    min_stock_alert: 5,
    specs_detail:
      "Multimeter digital dengan fungsi AC/DC, resistance, dan continuity",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-fis-2",
    lab_id: "mock-lab-2",
    category_id: "cat-fis-2",
    name: "Gaya Meter",
    code: "FIS-002",
    type: "alat",
    total_qty: 10,
    available_qty: 8,
    unit: "pcs",
    condition: "baik",
    location_rack: "Rak C-2",
    min_stock_alert: 3,
    specs_detail: "Gaya meter spring 0-10N, akurasi 0.1N",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-fis-3",
    lab_id: "mock-lab-2",
    category_id: "cat-fis-1",
    name: "Oscilloscope",
    code: "FIS-003",
    type: "alat",
    total_qty: 5,
    available_qty: 4,
    unit: "pcs",
    condition: "baik",
    location_rack: "Rak D-1",
    min_stock_alert: 2,
    specs_detail: "Oscilloscope digital 2 channel, 100MHz",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-fis-4",
    lab_id: "mock-lab-2",
    category_id: "cat-fis-2",
    name: "Set Optik",
    code: "FIS-004",
    type: "alat",
    total_qty: 8,
    available_qty: 7,
    unit: "set",
    condition: "baik",
    location_rack: "Rak D-2",
    min_stock_alert: 2,
    specs_detail: "Set optik lengkap dengan lensa, prisma, dan cermin",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-fis-5",
    lab_id: "mock-lab-2",
    category_id: "cat-fis-1",
    name: "Power Supply",
    code: "FIS-005",
    type: "alat",
    total_qty: 12,
    available_qty: 10,
    unit: "pcs",
    condition: "baik",
    location_rack: "Rak C-3",
    min_stock_alert: 4,
    specs_detail: "Power supply DC 0-30V, 5A, dengan display digital",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-fis-6",
    lab_id: "mock-lab-2",
    category_id: "cat-fis-3",
    name: "Kawat Nikrom",
    code: "FIS-006",
    type: "bahan",
    total_qty: 100,
    available_qty: 25,
    unit: "meter",
    condition: "baik",
    location_rack: "Lemari C1",
    min_stock_alert: 30,
    specs_detail: "Kawat nikrom diameter 0.5mm, tahan panas",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-fis-7",
    lab_id: "mock-lab-2",
    category_id: "cat-fis-2",
    name: "Ball Bearing",
    code: "FIS-007",
    type: "alat",
    total_qty: 50,
    available_qty: 45,
    unit: "pcs",
    condition: "baik",
    location_rack: "Rak D-3",
    min_stock_alert: 10,
    specs_detail: "Ball bearing 10mm, untuk eksperimen gesekan",
    created_at: new Date().toISOString(),
  },
];

// Mock Items for Lab Komputer
export const mockItemsKomputer: Item[] = [
  {
    id: "item-kom-1",
    lab_id: "mock-lab-3",
    category_id: "cat-kom-1",
    name: "Laptop Komputer",
    code: "KOM-001",
    type: "alat",
    total_qty: 30,
    available_qty: 28,
    unit: "pcs",
    condition: "baik",
    location_rack: "Meja 1-30",
    min_stock_alert: 25,
    specs_detail: "Laptop Intel Core i5, 8GB RAM, 256GB SSD, Windows 11",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-kom-2",
    lab_id: "mock-lab-3",
    category_id: "cat-kom-1",
    name: "Proyektor",
    code: "KOM-002",
    type: "alat",
    total_qty: 5,
    available_qty: 3,
    unit: "pcs",
    condition: "baik",
    location_rack: "Rumah Proyektor",
    min_stock_alert: 2,
    specs_detail: "Proyektor HD 3000 lumens, dengan HDMI",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-kom-3",
    lab_id: "mock-lab-3",
    category_id: "cat-kom-3",
    name: "Router WiFi",
    code: "KOM-003",
    type: "alat",
    total_qty: 3,
    available_qty: 2,
    unit: "pcs",
    condition: "baik",
    location_rack: "Rak Server",
    min_stock_alert: 1,
    specs_detail: "Router WiFi dual band, 300Mbps",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-kom-4",
    lab_id: "mock-lab-3",
    category_id: "cat-kom-1",
    name: "Monitor LCD",
    code: "KOM-004",
    type: "alat",
    total_qty: 10,
    available_qty: 9,
    unit: "pcs",
    condition: "baik",
    location_rack: "Rak Monitor",
    min_stock_alert: 3,
    specs_detail: "Monitor LCD 24 inch, Full HD",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-kom-5",
    lab_id: "mock-lab-3",
    category_id: "cat-kom-2",
    name: "Windows 11 Pro",
    code: "KOM-005",
    type: "bahan",
    total_qty: 35,
    available_qty: 32,
    unit: "lisensi",
    condition: "baik",
    location_rack: "Digital",
    min_stock_alert: 30,
    specs_detail: "Lisensi Windows 11 Pro OEM",
    expired_date: "2027-12-31",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-kom-6",
    lab_id: "mock-lab-3",
    category_id: "cat-kom-1",
    name: "Keyboard Mechanical",
    code: "KOM-006",
    type: "alat",
    total_qty: 25,
    available_qty: 22,
    unit: "pcs",
    condition: "baik",
    location_rack: "Rak Aksesoris",
    min_stock_alert: 8,
    specs_detail: "Keyboard mechanical cherry MX blue",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-kom-7",
    lab_id: "mock-lab-3",
    category_id: "cat-kom-1",
    name: "Mouse Gaming",
    code: "KOM-007",
    type: "alat",
    total_qty: 25,
    available_qty: 23,
    unit: "pcs",
    condition: "baik",
    location_rack: "Rak Aksesoris",
    min_stock_alert: 8,
    specs_detail: "Mouse gaming 16000 DPI, RGB",
    created_at: new Date().toISOString(),
  },
];

// Combined all items
export const mockAllItems: Item[] = [
  ...mockItemsKimia,
  ...mockItemsFisika,
  ...mockItemsKomputer,
];

// Mock Loans
export const mockLoans: Loan[] = [
  {
    id: "loan-1",
    item_id: "item-kim-1",
    borrower_name: "Ahmad Rizky",
    borrower_role: "siswa",
    loan_date: "2025-01-15T10:00:00Z",
    return_date: null,
    qty: 1,
    status: "dipinjam",
    notes: "Untuk praktikum kimia bab larutan",
    created_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "loan-2",
    item_id: "item-kim-2",
    borrower_name: "Siti Aminah",
    borrower_role: "guru",
    loan_date: "2025-01-14T09:00:00Z",
    return_date: "2025-01-14T15:00:00Z",
    qty: 5,
    status: "kembali",
    notes: "Demonstrasi kelas X-A",
    created_at: "2025-01-14T09:00:00Z",
  },
  {
    id: "loan-3",
    item_id: "item-fis-1",
    borrower_name: "Budi Santoso",
    borrower_role: "kepala_lab",
    loan_date: "2025-01-13T08:00:00Z",
    return_date: null,
    qty: 2,
    status: "dipinjam",
    notes: "Kalibrasi alat",
    created_at: "2025-01-13T08:00:00Z",
  },
  {
    id: "loan-4",
    item_id: "item-kim-3",
    borrower_name: "Dewi Lestari",
    borrower_role: "guru",
    loan_date: "2025-01-10T10:00:00Z",
    return_date: null,
    qty: 100,
    status: "rusak_hilang",
    notes: "Botol pecah saat penggunaan",
    created_at: "2025-01-10T10:00:00Z",
  },
  {
    id: "loan-5",
    item_id: "item-kom-1",
    borrower_name: "Rudi Hartono",
    borrower_role: "siswa",
    loan_date: "2025-01-12T14:00:00Z",
    return_date: "2025-01-12T17:00:00Z",
    qty: 1,
    status: "kembali",
    notes: "Pengerjaan tugas coding",
    created_at: "2025-01-12T14:00:00Z",
  },
  {
    id: "loan-6",
    item_id: "item-fis-2",
    borrower_name: "Fitri Handayani",
    borrower_role: "siswa",
    loan_date: "2025-01-16T08:30:00Z",
    return_date: null,
    qty: 1,
    status: "dipinjam",
    notes: "Praktikum gaya dan gerak",
    created_at: "2025-01-16T08:30:00Z",
  },
  {
    id: "loan-7",
    item_id: "item-kom-2",
    borrower_name: "Eko Prasetyo",
    borrower_role: "guru",
    loan_date: "2025-01-11T09:00:00Z",
    return_date: "2025-01-11T16:00:00Z",
    qty: 1,
    status: "kembali",
    notes: "Presentasi materi jaringan",
    created_at: "2025-01-11T09:00:00Z",
  },
];

// Export everything
export const mockData = {
  school: mockSchool,
  labs: mockLabs,
  categories: {
    kimia: mockCategoriesKimia,
    fisika: mockCategoriesFisika,
    komputer: mockCategoriesKomputer,
  },
  items: {
    kimia: mockItemsKimia,
    fisika: mockItemsFisika,
    komputer: mockItemsKomputer,
    all: mockAllItems,
  },
  loans: mockLoans,
};
