import { supabase } from "./supabase";
import { Lab } from "@/types/database";
import { createCategory } from "./supabase-categories";

export const DEFAULT_SCHOOL_ID = "11111111-1111-4111-8111-111111111111";

export function isValidUuid(value?: string | null) {
  if (!value) return false;
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
}

type LabQueryResultList = {
  data: Lab[] | null;
  error: unknown;
};

type LabQueryResultSingle = {
  data: Lab | null;
  error: unknown;
};

type LabQueryChain = {
  select: (columns?: string) => LabQueryChain;
  eq: (column: string, value: string) => LabQueryChain;
  order: (
    column: string,
    options?: { ascending?: boolean },
  ) => Promise<LabQueryResultList>;
  single: () => Promise<LabQueryResultSingle>;
  update: (payload: Record<string, unknown>) => LabQueryChain;
  delete: () => {
    eq: (column: string, value: string) => Promise<{ error: unknown }>;
  };
};

type LabCrudClient = {
  from: (table: "labs") => {
    select: (columns?: string) => LabQueryChain;
    insert: (rows: Array<Record<string, unknown>>) => LabQueryChain;
    update: (payload: Record<string, unknown>) => LabQueryChain;
    delete: () => {
      eq: (column: string, value: string) => Promise<{ error: unknown }>;
    };
  };
};

export async function getOrCreateDefaultSchool() {
  try {
    const client = supabase as unknown as {
      from: (table: "schools") => {
        select: (columns: string) => {
          eq: (column: string, value: string) => {
            maybeSingle: () => Promise<{
              data: { id: string } | null;
              error: { code?: string } | null;
            }>;
          };
        };
        upsert: (
          rows: Array<Record<string, unknown>>,
          options?: { onConflict?: string },
        ) => {
          select: (columns: string) => {
            single: () => Promise<{
              data: { id: string } | null;
              error: { code?: string } | null;
            }>;
          };
        };
      };
    };

    const { data: existingSchool, error: selectError } = await client
      .from("schools")
      .select("id")
      .eq("id", DEFAULT_SCHOOL_ID)
      .maybeSingle();

    if (selectError && selectError.code !== "PGRST116") {
      console.error("Error checking default school:", selectError);
    }

    if (existingSchool?.id) {
      return existingSchool.id;
    }

    const { data: createdSchool, error: upsertError } = await client
      .from("schools")
      .upsert(
        [
          {
            id: DEFAULT_SCHOOL_ID,
            name: "Default School",
            address: "Auto-generated by app",
            logo_url: null,
          },
        ],
        { onConflict: "id" },
      )
      .select("id")
      .single();

    if (upsertError) {
      console.error("Error creating default school:", upsertError);
      return DEFAULT_SCHOOL_ID;
    }

    return createdSchool?.id || DEFAULT_SCHOOL_ID;
  } catch (error) {
    console.error("Exception in getOrCreateDefaultSchool:", error);
    return DEFAULT_SCHOOL_ID;
  }
}

/**
 * Get all labs
 */
export async function getLabs() {
  const client = supabase as unknown as LabCrudClient;

  try {
    const { data, error } = await client
      .from("labs")
      .select("*")
      .order("name", { ascending: true });

    if (error) {
      console.error("Error fetching labs:", error);
      return [];
    }

    return data || [];
  } catch (error) {
    console.error("Exception in getLabs:", error);
    return [];
  }
}

/**
 * Get all labs with room count
 */
export async function getLabsWithRoomCount() {
  try {
    const { data, error } = await supabase
      .from("labs")
      .select("*, rooms(count)")
      .order("name", { ascending: true });

    if (error) {
      console.error("Error fetching labs with room count:", error);
      return [];
    }

    return data || [];
  } catch (error) {
    console.error("Exception in getLabsWithRoomCount:", error);
    return [];
  }
}

/**
 * Get lab by ID
 */
export async function getLabById(id: string) {
  const client = supabase as unknown as LabCrudClient;
  const { data, error } = await client
    .from("labs")
    .select("*")
    .eq("id", id)
    .single();

  if (error) {
    console.error("Error fetching lab:", error);
    throw error;
  }

  return data;
}

/**
 * Get labs by school ID
 */
export async function getLabsBySchool(schoolId: string) {
  const client = supabase as unknown as LabCrudClient;
  const { data, error } = await client
    .from("labs")
    .select("*")
    .eq("school_id", schoolId)
    .order("name", { ascending: true });

  if (error) {
    console.error("Error fetching labs by school:", error);
    throw error;
  }

  return data;
}

/**
 * Create new lab
 */
export async function createLab(
  lab: Pick<Lab, "school_id" | "name"> &
    Partial<Pick<Lab, "code" | "pic_name" | "description">>,
) {
  const client = supabase as unknown as LabCrudClient;

  try {
    const ensuredSchoolId = await getOrCreateDefaultSchool();
    const schoolId = isValidUuid(lab.school_id) && lab.school_id !== DEFAULT_SCHOOL_ID
      ? lab.school_id
      : ensuredSchoolId;

    const payload = {
      school_id: schoolId,
      code: lab.code ?? null,
      name: lab.name,
      pic_name: lab.pic_name ?? null,
      description: lab.description ?? null,
    };

    console.log("Creating lab with payload:", payload);

    const { data, error } = await client
      .from("labs")
      .insert([payload])
      .select()
      .single();

    if (error) {
      console.error("Error creating lab in Supabase:", {
        code: error instanceof Object && "code" in error ? error.code : "UNKNOWN",
        message: error instanceof Object && "message" in error ? error.message : String(error),
        details: error instanceof Object && "details" in error ? error.details : undefined,
        hint: error instanceof Object && "hint" in error ? error.hint : undefined,
      });
      throw new Error(`Failed to create lab: ${error instanceof Object && "message" in error ? error.message : String(error)}`);
    }

    if (!data) {
      throw new Error("No data returned from insert operation");
    }

    const createdLab = data as Lab;

    try {
      await Promise.all([
        createCategory({
          lab_id: createdLab.id,
          name: "Peralatan Umum",
          type: "asset",
        }),
        createCategory({
          lab_id: createdLab.id,
          name: "Bahan Praktikum",
          type: "consumable",
        }),
      ]);
    } catch (categoryError) {
      console.error("Warning: failed to create default categories for lab:", categoryError);
    }

    return createdLab;
  } catch (error) {
    console.error("Exception in createLab:", error);
    throw error;
  }
}

/**
 * Update existing lab
 */
export async function updateLab(id: string, lab: Partial<Lab>) {
  const client = supabase as unknown as LabCrudClient;

  try {
    const payload = { ...lab };
    delete payload.id;
    delete payload.created_at;
    delete payload.school_id; // Don't allow updating school_id
    delete payload.category; // Remove category field as it's not used in new schema
    delete payload.location; // Remove location field as it's not used in new schema

    console.log("Updating lab with payload:", payload);
    console.log("Lab ID:", id);

    const { data, error } = await client
      .from("labs")
      .update(payload)
      .eq("id", id)
      .select()
      .single();

    if (error) {
      console.error("Error updating lab:", {
        code: error instanceof Object && "code" in error ? error.code : "UNKNOWN",
        message: error instanceof Object && "message" in error ? error.message : String(error),
        details: error instanceof Object && "details" in error ? error.details : undefined,
        hint: error instanceof Object && "hint" in error ? error.hint : undefined,
      });
      throw new Error(`Failed to update lab: ${error instanceof Object && "message" in error ? error.message : String(error)}`);
    }

    if (!data) {
      throw new Error("No data returned from update operation");
    }

    return data as Lab;
  } catch (error) {
    console.error("Exception in updateLab:", error);
    throw error;
  }
}

/**
 * Delete lab
 */
export async function deleteLab(id: string) {
  const client = supabase as unknown as LabCrudClient;

  try {
    const { error } = await client.from("labs").delete().eq("id", id);

    if (error) {
      console.error("Error deleting lab:", error);
      return true;
    }

    return true;
  } catch (error) {
    console.error("Exception in deleteLab:", error);
    return true;
  }
}
